table rfm_segments
	lineageTag: 401fe1c3-bc98-43f5-98f7-e2147ea597a0

	column segment
		dataType: string
		lineageTag: f8cfe67f-84e9-471c-97f4-110d8df84430
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column customers
		dataType: int64
		formatString: 0
		lineageTag: fef69081-fc5c-4f77-948b-194e1cc856ad
		summarizeBy: sum
		sourceColumn: customers

		annotation SummarizationSetBy = Automatic

	column monetary
		dataType: double
		lineageTag: 81d7f139-36fb-4628-a920-be9369f66ebf
		summarizeBy: sum
		sourceColumn: monetary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_recency
		dataType: double
		lineageTag: bc6aea85-88bc-4c26-8124-535940fa6413
		summarizeBy: sum
		sourceColumn: avg_recency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_frequency
		dataType: double
		lineageTag: 5d3f13df-fae1-429a-b166-4818f7013e8f
		summarizeBy: sum
		sourceColumn: avg_frequency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_share
		dataType: double
		lineageTag: 5fe6ce3d-eaa5-4a76-b75c-09ff035fc2d4
		summarizeBy: sum
		sourceColumn: customer_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition rfm_segments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Pavithran R A\Documents\Codex\2026-09-04\goal-referenced-pasted-text-files-pasted\data\published\rfm_segments.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"segment", type text}, {"customers", Int64.Type}, {"monetary", type number}, {"avg_recency", type number}, {"avg_frequency", type number}, {"customer_share", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

